In [1]:
import numpy as np

In [2]:
np.abs(-38724)

38724

In [3]:
l1 = [1, 2, 3, 4]
l2 = [5, 6, 7, 8]

In [4]:
l1 + l2

[1, 2, 3, 4, 5, 6, 7, 8]

In [5]:
l2 - l1

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [6]:
arr1 = np.array(l1)
arr2 = np.array(l2)

In [8]:
arr1 + arr2

array([ 6,  8, 10, 12])

In [18]:
arr1 * arr2

array([ 5, 12, 21, 32])

In [10]:
type(arr1)

numpy.ndarray

In [19]:
np.dot(arr1, arr2)

70

In [20]:
np.transpose(arr2)

array([5, 6, 7, 8])

In [21]:
arr1.T

array([1, 2, 3, 4])

In [22]:
np.sum(arr1)

10

In [23]:
np.min(arr2)

5

In [29]:
np.reshape(arr1, (2,-1))

array([[1, 2],
       [3, 4]])

In [41]:
A = np.random.randint(10, 100, size=(5,5))

In [42]:
A

array([[18, 24, 45, 90, 39],
       [64, 58, 98, 12, 67],
       [76, 38, 71, 91, 70],
       [37, 53, 85, 25, 40],
       [85, 35, 88, 42, 12]])

In [44]:
A [2:5 , 2:4]

array([[71, 91],
       [85, 25],
       [88, 42]])

In [51]:
a = [[6, 2, 4, 6, 5]]

In [52]:
a + A

array([[ 24,  26,  49,  96,  44],
       [ 70,  60, 102,  18,  72],
       [ 82,  40,  75,  97,  75],
       [ 43,  55,  89,  31,  45],
       [ 91,  37,  92,  48,  17]])

In [53]:
A.flatten()

array([18, 24, 45, 90, 39, 64, 58, 98, 12, 67, 76, 38, 71, 91, 70, 37, 53,
       85, 25, 40, 85, 35, 88, 42, 12])

In [54]:
np.linalg.inv()

array([[-0.03458152, -0.02474299,  0.03171071,  0.01939049,  0.0009242 ],
       [-0.11002369, -0.13117919,  0.09776002,  0.16737764, -0.03819811],
       [ 0.07354158,  0.07860183, -0.07200805, -0.08538566,  0.02679548],
       [ 0.00175879, -0.01677058,  0.0084019 ,  0.01178937, -0.00038932],
       [ 0.0203942 ,  0.04015242, -0.01109851, -0.04063541, -0.00693945]])

In [ ]:
def distance(pA, pB):
    return 